### ISSUE TITLE
Automatically Update Date/Timestamp in HTML Before Building EPUB

### ISSUE THREAD

**Issue by paladhammika** [sasanarakkha/sasanarakkha-recitations-book#16]
@bergentroll 

```
# Update the date
cd manuscript/html/OEBPS/Text
TODAY=$(date --iso-8601)
sed -i 's/\(This version was created on:\) *[0-9-]\{10\}/\1 '"$TODAY"'/' copyright.xhtml
cd ../../..
```
The above is some `sed` magic which was used in earlier versions of this project. It automatically changed the time stamp (seen in the picture below) with each build. 

![image](https://user-images.githubusercontent.com/93992898/219373972-3fe69c1a-9084-42f4-a024-140572d2391a.png)

Attempts to implement this into the current Makefile have not been successful. Would you have any suggestions?

![image](https://user-images.githubusercontent.com/93992898/219377716-7319a809-37b2-4ff9-a6fb-d271482d2e39.png)

**Comment by bergentroll** [comment]
If you try to put `@echo [${PWD}]` after `cd ...`, bhante, you may note that `cd` takes not effect. It seems like shell specific in Make. You are able to use the following construction:

```make
        @sed -i 's/\(This version was created on:\) *[0-9-]\{10\}/\1 '"$TODAY"'/' manuscript/html/OEBPS/Text/copyright.xhtml
```

Or even this one:

```make
        @cd manuscript/html/OEBPS/Text && sed -i 's/\(This version was created on:\) *[0-9-]\{10\}/\1 '"$TODAY"'/' copyright.xhtml
```

There is also no need to do `cd ../../../` because it will not take effect too.

Also there will be a problem with the `$TODAY` variable. You may set and use it e.g. in a such way:
```make
TODAY=$(shell date --iso-8601)
...

epub: $(EPUBFILE)
$(EPUBFILE): $(SOURCEFILES)
        ...
        @sed -i 's/\(This version was created on:\) *[0-9-]\{10\}/\1 '"$(TODAY)"'/' manuscript/html/OEBPS/Text/copyright.xhtml
        ...
```

(`...` is for some other relative code).

❤️🙏🙏🙏

**Comment by paladhammika** [comment]
Sādhu! This was helpful.

I had to use sed within an enclosed shell command otherwise it would fail to produce the EPUB.


```make
@$(shell command sed -i 's/\(This version was created on:\) *[0-9-]\{10\}/\1 '"$(TODAY)"'/' manuscript/html/OEBPS/Text/copyright.xhtml)
````
